services:
  kafka1:
    image: ssamantr/kafka-broker:latest
    container_name: kafka-broker-1
    hostname: kafka1
    ports:
      - "8082:8082"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s1.properties:/kafka/config/kraft/server.properties
      - ./data/b1:/tmp/kafka-logs

  kafka2:
    image: ssamantr/kafka-broker:latest
    container_name: kafka-broker-2
    hostname: kafka2
    ports:
      - "8083:8083"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s2.properties:/kafka/config/kraft/server.properties
      - ./data/b2:/tmp/kafka-logs

  kafka3:
    image: ssamantr/kafka-broker:latest
    container_name: kafka-broker-3
    hostname: kafka3
    ports:
      - "8084:8084"
    environment:
      KAFKA_CLUSTER_ID: OTMwNzFhYTY1ODNiNGE5OT
    volumes:
      - ./props/s3.properties:/kafka/config/kraft/server.properties
      - ./data/b3:/tmp/kafka-logs

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka1:9092,kafka2:9092,kafka3:9092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
    depends_on:
      - kafka1
      - kafka2
      - kafka3