name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Maven Verify
        run: |
          ./mvnw --batch-mode --no-transfer-progress -B verify -pl avro-schema-registry/order-service-avro/consumer/,avro-schema-registry/order-service-avro/producer/,avro-schema-registry/order-service-avro/greetings-app  -am